#! /usr/bin/env python3

import platform
from lens.app import App

app = App(name="Lens. Splash")

@app.bind('close')
def _close_app_cb(*args):
    app.close()

# set up async timer to fire in 5 seconds
def _preload():
    app.emit('loaded')

app.timer(3000, _preload, once=True)

# start the app event loop
app.start("""
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <link href="lens://css/lens.css" rel="stylesheet">
    <style>
        .splash {
          position: absolute;
          left: 0;
          top: 0;
          right: 0;
          bottom: 0;
          z-index: 1000;
          background-color: #fff;
          transition: all 1.0s;
        }

        .loaded .splash {
          opacity: 0;
          z-index: -1;
        }

        .loading,
        .loading::before,
        .loading::after {
          position: absolute;
          top: 50%;
          left: 50%;
          border: 1px solid rgba(0, 0, 0, 0.1);
          border-left-color: rgba(0, 0, 0, 0.4);
          border-radius: 999px;
        }

        .loading {
          margin: -25px 0 0 -25px;
          height: 50px;
          width: 50px;
          animation: animation-rotate 1000ms linear infinite;
        }

        .loading::before {
          content: "";
          margin: -23px 0 0 -23px;
          height: 44px;
          width: 44px;
          animation: animation-rotate 1000ms linear infinite;
        }

        .loading::after {
          content: "";
          margin: -29px 0 0 -29px;
          height: 56px;
          width: 56px;
          animation: animation-rotate 2000ms linear infinite;
        }

        @keyframes animation-rotate {
          100% {
            transform: rotate(360deg);
          }
        }
    </style>
  </head>
  <body>
    <div class="splash">
      <div class="loading"></div>
    </div>

    <h1>Lens. Splash</h1>
    <p>This sample demonstrates simple communication between the Python and JS code paths by presenting a simple splash screen where the "pre-loading" occurs on the Python side.</p>
    <div class="text-center">
      <button id="closeBtn">CLOSE</button>
    </div>

    <script src="lens://js/lens.js"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function(event) {
        document.getElementById("closeBtn").onclick = function() {
          lens.emit('close');
        };

        lens.on('loaded', function(e) {
          document.body.className = "loaded";
        });
      });
    </script>
  </body>
  </html>
""")
