#!/usr/bin/python3
#
# Copyright 2012-2017 "Korora Project" <dev@kororaproject.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the temms of the Lesser GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# Lesser GNU General Public License for more details.
#
# You should have received a copy of the Lesser GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

import logging
import platform
import pprint

from lens.app import App

class MyApp(App):
    def __init__(self):
        App.__init__(self, name="Lens. Widgets", inspector=True)

        self.namespaces = ['./data']

        self.on('close', self._close_app_cb)
        self.on('get-hostname', self._get_hostname_cb)
        self.on('update-hostname', self._update_hostname_cb)
        self.on('toggle-window-fullscreen', self._fullscreen_cb)
        self.on('toggle-window-maximize', self._maximize_cb)

    def _close_app_cb(self, *args):
        self.close()

    def _get_hostname_cb(self, *args):
        self.emit('update-config', platform.node())

    def _update_hostname_cb(self, message):
        pp = pprint.PrettyPrinter(indent=2)
        pp.pprint(message)

    def _fullscreen_cb(*args):
        app.toggle_window_fullscreen()

    def _maximize_cb(*args):
        app.toggle_window_maximize()


logging.basicConfig(level=logging.DEBUG)

app = MyApp()

app.start()

